### ISSUE TITLE
Ego Application Initialization

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#538]
# Problem
Currently, after ego is booted for the first time, a user tries to login via the ego-ui, which causes their user to be created in ego as a USER role. If the user wants to create permissions, applications etc, they require the ADMIN role. To achieve this, they send a request to a sys-admin who then logs in to the database and executes a UPDATE sql command.

This is extremely invasive. NO ONE should be able to nor need to login to the database.

# Solution
A simple solution, is to provide the option for ego to be first-time booted with initializing applications. Using an application's clientId and clientSecret, ego can be controlled, which eliminates the need to login to the database

# Example
By setting the following in the application.yml:
```yaml
initialization:
  enabled: true
  applications:
    - name: my-app
      type: ADMIN
      clientId: myClientId
      clientSecret: myClientSecret123
      redirectUri: https://example.org  # optional
      description: Some description about this application  # optional
```
once ego is booted for the first time (the first time means, there is no flyway table in the database yet), the applications listed in the appication.yml will be created. Using those credentials, an app-jwt can be generated and the UpdateUser endpoint can be called to set the users role from USER to ADMIN

First-time boot is detected using a tripwire. Upon boot, the application will check if the tripwire was tripped. If no, it will initialize the applications. If it was, it will not. So if ego is booted for the first time without any applications specified, the trip wire will be set, and there will no longer be any opportunities to initialize applications on subsequent boots.
